name: CI/CD Build & Deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build_and_store_dnn_extensions:
    runs-on: windows-latest
    name: Build And Store
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v2.0.0
    
    - name: Restore NuGet Packages
      run: nuget restore './ExpandableTextHtml.sln'
    
    - name: Build the solution
      run: msbuild './ExpandableTextHtml.sln' /p:Configuration=Release;
      
    - name: Collect Installers
      if: github.event_name != 'pull_request'
      run: |
        md installers
        Get-ChildItem -Include *install.zip -Recurse | Copy-Item -Destination "installers\"
      shell: powershell
      working-directory: .\
  
    - name: Store Install Package
      if: github.event_name != 'pull_request'
      uses: actions/upload-artifact@v4
      with:
        name: installers
        path: './installers/**_install.zip'
        retention-days: 5 # only need long enough to test/validate 